// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  fullWidth: string;
  root: string;
  yellowButton: string;
}
export const cssExports: CssExports;
export default cssExports;
