// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  root: string;
  subtitle: string;
  textBlock: string;
  title: string;
  titleSpan: string;
  wrapper: string;
}
export const cssExports: CssExports;
export default cssExports;
