// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  error: string;
  images: string;
  r: string;
  root: string;
  title: string;
}
export const cssExports: CssExports;
export default cssExports;
