// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  error: string;
  imageBlock: string;
  root: string;
  wrap: string;
}
export const cssExports: CssExports;
export default cssExports;
